#include "Protheus.ch"       

/*/{Protheus.doc} F420SOMA
Function Rotina usada para declarar as variáveis publicas necessárias para a geração do sispag
@type function
@version 12.1.2310
@author TOTVSIP | Alexandre Luis Eugenio
@since 31/07/2024
@return logic, .T.
/*/

User Function FA420CRI()       

    Public _nTotEnt     := 0
    Public _nTotAcres   := 0
    Public _nTotGps     := 0
    Public _nTotAbat    := 0
    Public _cChavSpag   := ""

Return .T.
