#include "totvs.ch"
#include "tlpp-core.th"
#include "tlpp-object.th"

/*/{Protheus.doc} FISTRFNFE
Ponto de entrada que inclui mais opções
de rotinas na rotina SPEDNFE.
@type  Function
@author Raphael Koury Giusti
@since 08/11/2023
/*/
user function FISTRFNFE()
    default aRotina := {}

        aadd(aRotina,{"Danfe | Dux"             ,"u_ImprimeNotaFiscal(1)",0,3,0,nil})
        aadd(aRotina,{"Danfe Etiqueta | Dux"    ,"u_ImprimeNotaFiscal(2)",0,3,0,nil})

return 
